qdisk: set filename sooner
syslog-ng/syslog-ng pull request #4383
Opened 2023-03-22 13:38 UTC by alltilla

This PR is a preparation step for #4356.

There, we will need to know the filename when creating a `LogQueueDisk` instance in order to properly setup the `StatsClusterKey` for the metrics.

No news file needed.

Signed-off-by: Attila Szakacs <attila.szakacs@axoflow.com>

2023-03-22 14:26 UTC, kira-syslogng commented
Kira-stress-test: Build SUCCESS

2023-03-23 10:38 UTC, alltilla commented
@kira-syslogng do stresstest

2023-03-23 11:03 UTC, kira-syslogng commented
Kira-stress-test: Build SUCCESS

2023-03-28 20:08 UTC, MrAnno requested changes

2023-03-29 10:12 UTC, alltilla commented on modules/diskq/qdisk.c
> +  if (next_filename && !_init_qdisk_file_from_empty_file(self, next_filename))
Nice catch, fixed.

--

About the UT, I will try to implement one in a commit on top.

2023-03-29 10:12 UTC, alltilla commented on modules/diskq/diskq.c
> +  log_queue_set_throttle(queue, dd->throttle);
True, fixed.

2023-03-29 10:13 UTC, alltilla commented on modules/diskq/diskq.c
> +    _save_filename_to_persist(cfg->state, persist_name, log_queue_disk_get_filename(queue));
Agree, fixed.

2023-03-29 13:30 UTC, alltilla commented
@kira-syslogng do stresstest

2023-03-29 13:55 UTC, kira-syslogng commented
Kira-stress-test: Build SUCCESS

2023-03-30 05:17 UTC, MrAnno approved these changes

2023-03-30 05:21 UTC, merged