Fix cmake builds zlib link issues
syslog-ng/syslog-ng pull request #4601
Opened 2023-08-22 08:17 UTC by HofiOne

cmake: fixed linker issues after http module changes

also added some cmake scripts simplifying and enhancements

Signed-off-by: Hofi <hofione@gmail.com>

2023-08-23 16:31 UTC, MrAnno requested changes

2023-08-23 20:05 UTC, HofiOne commented on CMakeLists.txt
> -  add_subdirectory(tests)
hmm, but if 

```
macro (add_test_subdirectory SUBDIR)
  if (BUILD_TESTING)
    add_subdirectory(${SUBDIR})
  endif()
endmacro()
```

than the old one will be expanded to something like this

```
if (BUILD_TESTING)
  if (BUILD_TESTING)
    add_subdirectory(libtest)
  endif()
  add_subdirectory(tests)
endif()
```

which should be equal to the new version

```
  if (BUILD_TESTING)
    add_subdirectory(libtest)
  endif()
  if (BUILD_TESTING)
    add_subdirectory(tests)
  endif()
```

surely it's my bad, but cannot see the difference

2023-08-24 08:57 UTC, MrAnno commented on CMakeLists.txt
> -  add_subdirectory(tests)
Sorry, it's my bad; this was incorrect originally. Your modification is indeed equivalent.

We should not make the root `tests` folder `BUILD_TESTING`-dependent, as they don't contain any tests to build anymore. loggen, light, and functional tests should not be excluded when `BUILD_TESTING` is disabled.

The only directory we should skip is `tests/loggen/tests`.

2023-08-24 09:12 UTC, HofiOne commented on CMakeLists.txt
> -  add_subdirectory(tests)
> We should not make the root `tests` folder `BUILD_TESTING`-dependent, as they don't contain any tests to build anymore. loggen, light, and functional tests should not be excluded when `BUILD_TESTING` is disabled.
> I might be wrong about light and func tests, but `loggen` is not considered a build test, it is a packaged testing tool for end users.

let's make this than in a separate test fix commit
I remove this change from this PR
what do you say?

2023-08-24 09:30 UTC, MrAnno approved these changes

2023-08-24 09:31 UTC, merged