logthrdest: add syslogng_output_event_retries_total metric
syslog-ng/syslog-ng pull request #4807
Opened 2024-01-29 14:05 UTC by alltilla

Example metrics:
```
syslogng_output_event_retries_total{driver="http",url="http://localhost:8888/${path}",id="#anon-destination0#0"} 5
```

2024-01-30 11:51 UTC, MrAnno commented on lib/logthrdest/logthrdestdrv.c
> +    stats_counter_inc(self->owner->metrics.output_event_retries);
(Around `_rewind_batch()`, or on the error paths of `_process_result()`.)

2024-01-30 11:51 UTC, MrAnno requested changes
Reload is a problem here.
With `event_retries`, I think we want to indicate when something went wrong with event delivery.

Multiple `connect` calls are normal within syslog-ng. I think even multiple `disconnect()` calls are normal.
Why don't we increase this counter where actual errors happen during send/flush?

(Around _rewind_batch(), or on the error paths of _process_result().)

2024-01-30 11:57 UTC, alltilla commented
Good point. I did not put the counter increase in the error handling functions, because it is only retried after the next connect, which happens after time-reopen, which is 1 minute by default. So we increase the counter 1 minute earlier, but maybe we can live with that. What do you think?

2024-01-30 12:26 UTC, MrAnno commented
I think we can live with that :)

2024-01-30 14:19 UTC, alltilla commented
Moved it to the result handling functions and it happened to end up around `rewind_batch()`, which is a good indication that it is in the correct place. :) Thanks for the suggestion.

2024-01-30 18:03 UTC, MrAnno commented
Thank you. A last question: can't we actually put this into `rewind_batch()`? I see that every call of that function precedes the metric update. `rewind_batch()` is the most direct way of saying "we will retry this" in my opinion, so probably the metric belongs there and remains correct even if we introduce more error paths.

2024-01-30 19:32 UTC, alltilla commented
To me it felt a bit side-effecty. If we put it there, I feel like we should rename the function. I will try to come up with something, and if I cannot find, I will just put the stats increase there and not rename it.

2024-01-31 08:32 UTC, alltilla commented
@MrAnno Could not come up with a better name :)

2024-01-31 08:58 UTC, MrAnno commented
I don't think we need a better name, recording metrics are normal side-effects.

2024-01-31 08:58 UTC, MrAnno approved these changes

2024-01-31 08:58 UTC, merged