disable publishing docker image to Docker Hub
syslog-ng/syslog-ng pull request #4985
Opened 2024-06-05 14:04 UTC by folti

2024-06-05 19:37 UTC, kira-syslogng commented
Build FAILURE

2024-06-06 10:58 UTC, kira-syslogng commented
Build FAILURE

2024-06-06 11:02 UTC, folti commented
@kira-syslogng please rebuild

2024-06-06 11:13 UTC, folti commented
@kira-syslogng test this please;

2024-06-06 11:19 UTC, kira-syslogng commented
Build FAILURE

2024-06-06 13:11 UTC, kovgeri01 commented on lib/ivykis
You accidentally updated the `ivykis` submodule which causes the tests to fail can you revert this?

2024-06-06 13:12 UTC, kovgeri01 requested changes

2024-06-06 13:20 UTC, folti commented on lib/ivykis
done

2024-06-07 10:54 UTC, HofiOne approved these changes

2024-06-07 10:56 UTC, kovgeri01 approved these changes

2024-06-07 12:03 UTC, HofiOne commented
Credentials are fixed, publish is fine, closing.

2024-06-07 12:03 UTC, closed without merging