Add missing inttypes.h and define __STDC_FORMAT_MACROS if undefined
syslog-ng/syslog-ng pull request #5094
Opened 2024-09-11 15:34 UTC by barracuda156

Some platforms need `inttypes.h` and `__STDC_FORMAT_MACROS` defined prior to including it in order for macros like `PRIu64` to work. Fix that.

2024-09-11 15:34 UTC, kira-syslogng commented
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
"add to whitelist" add author of a Pull Request to whitelist (globally, be careful, it means this user can trigger kira for any PR)
do nothing -> CI won't start)

2024-09-11 15:34 UTC, kira-syslogng commented
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
"add to whitelist" add author of a Pull Request to whitelist (globally, be careful, it means this user can trigger kira for any PR)
do nothing -> CI won't start)

2024-09-12 11:07 UTC, HofiOne commented
@kira-syslogng ok to test;

2024-09-13 11:32 UTC, HofiOne requested changes

2024-09-13 11:32 UTC, HofiOne commented on modules/geoip2/maxminddb-helper.c
> +
this one cries for me for a commonplace somewhere, instead of the repeated inclusion, but could not find the best one for it yet...

2024-09-13 11:32 UTC, HofiOne commented on modules/geoip2/maxminddb-helper.c
> +
ok, `lib/compat`` dir will do the trick

please create a `lib/compat/inttypes.h` or similar file

and include that one where needed

2024-09-13 17:05 UTC, HofiOne commented
@barracuda156 One more tiny issue. All the PRs fail now in the commit (format) check, you can see the requirements e.g. [here](https://github.com/syslog-ng/syslog-ng/actions/runs/10814891169/job/30049170697?pr=5094)
Could you please amend your commits and fix the format problems?
TIA!

2024-09-13 19:02 UTC, barracuda156 commented
@HofiOne Yeah, sure. Just done with rebuilding gcc, now can sort out everything, hopefully.

2024-09-17 10:09 UTC, HofiOne commented
Moved this to https://github.com/syslog-ng/syslog-ng/pull/5108
Credits added, thank you for the contribution!

2024-09-17 10:09 UTC, closed without merging

2024-09-17 10:26 UTC, barracuda156 commented
@HofiOne Great, thank you.