Logrotate support
syslog-ng/syslog-ng pull request #5191
Opened 2024-11-27 14:09 UTC by azike

## Description
This pull-requests adds support for filesize-based logrotation (inspired by  https://github.com/syslog-ng/syslog-ng/pull/4145+-) to counter problems with constraints on logfile partition sizes.
Limits on file size and number of rotations (history) are defined in the conf file and the destination driver makes sure to rotate logfiles after they reached the defined size.

## Overview
The implementation is added directly to the `affile` module, as it is only effecting file destinations using regular-files. Keywords to allow setting logrotation options, like the maximum file size and number of rotations, are added to `affile-grammar`.

The `AFFileDestDriver` objects of the file destination holds a new field containing the logrotation settings (defined in `modules/affile/logrotate.h`), which are valid for all its writers of type `AFFileDestWriter`. 
After the writer worker-thread performed its task (`log_writer_work_perform`) and flushed the incoming messages (`log_writer_flush_finalize`) it notifies its controlling `AFFileDestWriter` instance via `log_pipe_notify`.  The actual checks, if rotation is to be performed, and the rotation itself are done in `affile-dest.c` and triggered through the notification.

During rotation the current logfile is renamed, therefore it has to be opened again. As the rotation is triggered from withing the worker-thread, a call to `affile_dw_reopen` would lead to a deadlock (thread waits on itself). The reopen is done by simply updating the `fd` of the `LogProtoClient` (no other thread modifies the `LogProtoClient` while it is still at work).
Alternatively a blocking main-thread call to open the file is possible, but I don't think it is necessary.

The main-thread watches are again registered afterwards in `log_writer_work_finished`.

## Usage
Below is an example conf file which uses an `example_msg_generator` source to emit 1000 messages. The file destinations are annotated with the `logrotate(...)` keyword specifying its rotation settings. Macros in the filename are still possible:
```
@version: 4.8
@include "scl.conf"

source s_sys{
    system();
};

source s_gen {
    example_msg_generator (
        num(1000)
        freq(0.001)
        template("Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut")
    );
};

# works with MACROs
destination d_file1 {
    file("/tmp/logfile_$HOST.log", logrotate(enable(yes), size(30KB), rotate(5)));
};

destination d_file2 {
    file("/tmp/logfile_simple.log", logrotate(enable(yes), size(20KB), rotate(3)));
};

log {
    source(s_gen);
    source(s_sys);
    destination(d_file1);
    destination(d_file2);
};
```

## TODO's and ideas
1) Up until now only filesize based rotation is implemented.
2) No support for compression of rotated files (which might be possible to schedule in a different thread).
3) On high load imposed by the message source the additional delay through rotation may lead to flow-control and the suspension of the source. I only tested it with the `example_msg_generator` source set to `freq(0.0001)`, which lead to message loss. However, I am not sure it that frequency is realistic or how other type of source behave when being suspended. 
4) Maybe it makes sense to outsource the renaming of already rotated logfiles to another thread.

## Related topics
Resolves #2964
Documentation PR https://github.com/syslog-ng/syslog-ng.github.io/pull/240

2024-11-27 14:09 UTC, kira-syslogng commented
Can one of the admins verify this patch?

2024-11-27 14:09 UTC, kira-syslogng commented
Can one of the admins verify this patch?

2024-11-28 14:17 UTC, azike commented
I updated the branch since the pipeline failed previously. Could you restart the checks?

2025-01-08 07:09 UTC, azike commented
Hi!
Are there any updates or suggestions from the maintainer team regarding this PR?

2025-01-28 12:51 UTC, BeBinder commented
Will this patch be included in future versions of syslog-ng?

2025-02-21 12:55 UTC, HofiOne commented
@azike, @BeBinder sorry for the delay, we will pick this up in the near future hopefully, it is at the top of our list, thank you!

2025-03-04 11:22 UTC, HofiOne commented
@azike could you please re-target the PR to the `develop` branch, from now and on we will use that one primarily for development, master will be dedicated to release builds
thank you!

2025-03-04 15:02 UTC, azike commented
Alright! Thank you.

2025-03-04 15:37 UTC, HofiOne requested changes

2025-03-04 15:37 UTC, HofiOne commented on modules/affile/affile-dest.c
> +          if (open_result != FILE_OPENER_RESULT_SUCCESS) return FALSE;
Please do not use this if construct, use a separate line for the better readability (one more TODO in the .astylerc)

2025-03-04 15:37 UTC, HofiOne commented on modules/affile/affile-dest.c
> + *      main_loop_call((MainLoopTaskFunc) affile_dw_reopen, (gpointer) self, TRUE);
Or even better, just notifying via NC_REOPEN_REQUIRED, but none of them could work anyway, I guess.

Any possibility of an operation attempt on the already closed fd between the close and re-open could lead issues, e.g. triggering/reporting an error.

So, I think "manually" and instantly reopening the file is the correct solution, but not exactly the way you did bellow, please see there.

2025-03-04 15:37 UTC, HofiOne commented on modules/affile/affile-dest.c
> +          FileOpenerResult open_result = file_opener_open_fd(self->owner->file_opener, self->filename, AFFILE_DIR_WRITE, fd);
As you described, direct call of the current form of `affile_dw_reopen` cannot be used here, but I think we need all the logic it has (e.g. setting last_open_stamp), so I suggest the following to avoid code duplication and stay consistent.

- split affile_dw_reopen
- move the main part of it to a new function (e.g. `_do_reopen` or similar) that returns the newly created `LogProtoClient`, if any 
  - take care of calling `file_opener_construct_transport` only if it is not presented yet
- leave only calling `log_writer_reopen` at the end and call/parametrize it based on the returned `LogProtoClient` instance, if any
- call the new `_do_reopen` here instead of `file_opener_open_fd`

2025-03-11 09:27 UTC, azike commented on modules/affile/logrotate.c
> +  if(g_file_test(current_filename, G_FILE_TEST_EXISTS))
Done

2025-03-11 09:27 UTC, azike commented on modules/affile/logrotate.c
> +      msg_error("LOGROTATE: Error reading file stats",
Done

2025-03-11 09:28 UTC, azike commented on modules/affile/affile-grammar.ym
> +		else affile_dd_set_logrotate_rotations(last_driver, $3);}
Done

2025-03-11 09:28 UTC, azike commented on modules/affile/affile-dest.c
> + * This function checks is logrotation should be performed based on the current
Fixed

2025-03-11 09:28 UTC, azike commented on modules/affile/affile-dest.c
> +          if (open_result != FILE_OPENER_RESULT_SUCCESS) return FALSE;
Done

2025-03-11 09:34 UTC, azike commented on modules/affile/affile-dest.c
> +          FileOpenerResult open_result = file_opener_open_fd(self->owner->file_opener, self->filename, AFFILE_DIR_WRITE, fd);
Fixed! Please review if it aligns with your description. The call too `file_opener_construct_transport` happens everytime to update the `fd`. In `lib/logwriter` only the 'old' `proto` is cleared and the new one is set (no manual update of `fd` is necessary).
If you still prefer to update the `fd` in `logwriter` as before and call `file_opener_construct_transport` conditionally I can change it.

2025-03-11 09:35 UTC, azike commented on modules/affile/affile-dest.c
> + *      main_loop_call((MainLoopTaskFunc) affile_dw_reopen, (gpointer) self, TRUE);
See comment below.

2025-03-11 09:41 UTC, azike commented on lib/logwriter.c
>      }
Here it is checked if the call to `log_pipe_notify` returns a new `LogProtoClient`. But I guess some error handling may be necessary, e.g. what happens if the reopen fails (`proto == NULL`)? Should the Writer be reaped and its queue flushed? 
A call `log_pipe_notify(self->control, NC_CLOSE, NULL)` does not work because it has to happen in the main thread and the Writer should not be active.

2025-03-13 07:18 UTC, azike commented
I updated the last commit message since the `commits check` pipeline failed.

2025-03-13 12:38 UTC, HofiOne commented on modules/affile/affile-dest.c
> +          FileOpenerResult open_result = file_opener_open_fd(self->owner->file_opener, self->filename, AFFILE_DIR_WRITE, fd);
> The call to `file_opener_construct_transport` happens everytime to update the `fd`. In `lib/logwriter` only the 'old' `proto` is cleared and the new one is set (no manual update of `fd` is necessary).
> If you still prefer to update the `fd` in `logwriter` as before and call `file_opener_construct_transport` conditionally I can change it.

No, this version is nice as it is, thanks. (We normally should not touch the fd directly ever, I guess)

2025-03-13 13:17 UTC, azike commented on lib/logproto/logproto-client.h
> +
Then I guess we can remove this function (and `log_transport_update_fd` in `logtransport.c`)? Since now it is not needed anymore.

2025-03-13 13:24 UTC, HofiOne commented on lib/logproto/logproto-client.h
> +
yes, definietly

2025-03-13 13:40 UTC, azike commented on lib/logproto/logproto-client.h
> +
Done! If you want me to squash the commits later on (after the review is done) let me know.

2025-03-13 13:54 UTC, HofiOne commented on lib/logproto/logproto-client.h
> +
> Done! If you want me to squash the commits later on (after the review is done) let me know.

Yes, after we finished, please squash for the possible minimum (but do not take it too seriously, if a given sequence requires a lot of effort, just leave as it is)

2025-03-13 14:38 UTC, HofiOne commented on lib/logwriter.c
>      }
Reviewing this a bit better I can see the following:

- here we now miss a case that earlier was handled separately, the case when the failure cause was NOT `FILE_OPENER_RESULT_ERROR_PERMANENT`, which was handled nicely by `log_writer_reopen/log_writer_reopen_deferred` (via a continuous re-open attempt)
this, now missing case, must be restored, e.g. `LogProtoClient *
_dw_reopen(AFFileDestWriter *self)` must become `FileOpenerResult _dw_reopen(AFFileDestWriter *self, LogProtoClient **)`
- what we should figure out is how to handle the `FILE_OPENER_RESULT_ERROR_PERMANENT` case

Checking all the calls of `affile_dw_reopen` I can see that in most cases `affile_dw_reopen` is simply initiated directly (or (re-)scheduled) for a later attempt.
In our case, only the re-schedule can be a solution,  we can use `main_loop_call` to achive that.

2025-03-17 10:57 UTC, azike commented on modules/affile/affile-dest.c
> +              log_writer_reopen_logrotate(self->writer);
I tried something to account for transient errors, please have a look.
In case of a transient error the function `log_writer_reopen_deferred` is called to reschedule the callback to reopen the log file. In this case we free the `LogProtoClient` of the `LogWriter` (`proto = NULL`)  to signal its absence (otherwise writing messages will be continued using the last rotated log file).

However, this alone can lead to overshooting the maximum file size if the incoming message buffer is filled in the reopen timeout period.
Currently the `logrotate` check is done in `log_writer_flush_finalize` (after the buffer is empty). I put it there to avoid call `stat` after every outgoing message.
Now we should put the check inside `log_writer_flush` to account for the full buffer. To mitigate potential performance problems the checks could be scheduled after every `n-th` outgoing message.

2025-03-17 10:58 UTC, azike commented on lib/logwriter.c
>      }
Thanks for the feedback. See discussion below.

2025-03-17 11:00 UTC, azike commented on lib/logwriter.c
> +        return FALSE;;
Doing the `logrotate` check here means it could be removed from `log_writer_flush_finalize`.

2025-03-17 11:05 UTC, azike commented on modules/affile/affile-dest.c
> +              log_writer_reopen_logrotate(self->writer);
Instead of calling `log_writer_reopen_deferred` directly (through `log_writer_reopen_logrotate`) one could do a main-loop call to `affile_dw_reopen` like:
`main_loop_call((MainLoopTaskFunc) affile_dw_reopen, (gpointer) self, TRUE);`
`affile_dw_reopen` will immediately try again to open the file, which resolves the problems if successful, and others again calls `log_writer_reopen_deferred` to reschedule the callback.
However, when using this one should make sure to reset the `LogProtoClient` as described above.

2025-03-17 14:03 UTC, HofiOne requested changes

2025-03-17 14:03 UTC, HofiOne commented on lib/logwriter.c
> +{
I do not think we need this function, `log_writer_reopen` would do the trick as the `log_writer_reopen_deferred` will handle the `log_writer_free_proto` part too.
Or, am I missing something here?

2025-03-17 14:03 UTC, HofiOne commented on modules/affile/affile-dest.c
> +              log_writer_reopen_logrotate(self->writer);
please see my comments
apart from that, I think I have to start debugging and testing it much better as it gets a bit complicated now,

2025-03-17 15:07 UTC, azike commented on lib/logwriter.c
> +      log_writer_logrotate(self);
I agree.  But still checking for logrotation after every outgoing message seems a bit overkill.

2025-03-17 15:11 UTC, azike commented on lib/logwriter.c
> +{
Yeah your are right. If `log_writer_reopen_deferred` is called with `proto == NULL`  this should do the same thing. Although in `affile_dw_logrotate` the main-loop call should be blocking, to not accidentally start the writer thread again with the 'old' `proto`.

2025-03-17 15:11 UTC, azike commented on modules/affile/affile-dest.c
> +      if (status == LR_SUCCESS)
Done

2025-03-17 15:12 UTC, azike commented on modules/affile/affile-dest.c
> +  //return open_result;
Thanks

2025-03-17 15:12 UTC, azike commented on modules/affile/affile-dest.c
> +          if (open_result == FILE_OPENER_RESULT_ERROR_TRANSIENT)
Yeah sure. I missed that one.

2025-03-17 15:12 UTC, azike commented on modules/affile/affile-dest.c
> +              msg_info("Transient error when opening file", evt_tag_str("filename", self->filename));
Done

2025-03-17 15:15 UTC, azike commented on lib/logwriter.c
> +{
However, `log_writer_reopen` can not be called directly because it would be called from within the worker thread and again deadlock itself. Hence one needs to go via the main-loop call of `affile_dw_reopen`.

2025-03-17 15:19 UTC, azike commented
I added the changes you suggested, but as I already stated we should somehow limit the number of logrotate checks. Doing it for every message could cost performance and in the end logs. If I run my [functional-test](https://github.com/azike/syslog-ng/blob/syslog-ng-logrotation/tests/light/functional_tests/destination_drivers/file_destination/test_file_destination.py) with `make light-check`, it fails now because I guess the sink can not keep up.

2025-03-17 15:25 UTC, azike commented on lib/logwriter.c
> +      log_writer_logrotate(self);
Maybe it makes sense to keep the check in `log_writer_flush_finalize` (in case the buffer is small) and do conditional checks if some upper bound is exceeded: 
1) message-count, 
2) or maybe even track the exact size of the messages written.

2025-03-17 15:42 UTC, HofiOne commented on lib/logwriter.c
> +      log_writer_logrotate(self);
If we had the file size cached (reading it at the init and then maintaining it at every write), we wouldn't need the double `log_writer_logrotate` call at all and could check the limit reach at a low cost, I think

2025-03-17 15:45 UTC, HofiOne commented
> I added the changes you suggested, but as I already stated we should somehow limit the number of logrotate checks. Doing it for every message could cost performance and in the end logs. If I run my [functional-test](https://github.com/azike/syslog-ng/blob/syslog-ng-logrotation/tests/light/functional_tests/destination_drivers/file_destination/test_file_destination.py) with `make light-check`, it fails now because I guess the sink can not keep up.

yepp, plz see my comment above, I guess a size caching can solve this too

2025-03-20 15:23 UTC, azike commented
I just checked it briefly but what I found out is that the `LogWriter` object keeps track of some metrics including `written_bytes`, which should get updated [here](https://github.com/syslog-ng/syslog-ng/blob/develop/lib/logwriter.c#L1273). However, as it seems the underlying counter is not initialized and set to [NULL](https://github.com/syslog-ng/syslog-ng/blob/develop/lib/stats/stats-compat.h#L68C1-L71C5). I did not dig any deeper but I guess the should be a good starting point. 
If we can keep track of the `written_bytes` per writer the size check can be done in memory only and when the limit is reached, the actual file size can be verifyied using `stat`.

I am away for three weeks now so, you will not hear any updates from me in that time.

2025-03-20 16:28 UTC, HofiOne commented
> I just checked it briefly but what I found out is that the `LogWriter` object keeps track of some metrics including `written_bytes`, which should get updated [here](https://github.com/syslog-ng/syslog-ng/blob/develop/lib/logwriter.c#L1273). However, as it seems the underlying counter is not initialized and set to [NULL](https://github.com/syslog-ng/syslog-ng/blob/develop/lib/stats/stats-compat.h#L68C1-L71C5). I did not dig any deeper but I guess the should be a good starting point. If we can keep track of the `written_bytes` per writer the size check can be done in memory only and when the limit is reached, the actual file size can be verifyied using `stat`.
> 
> I am away for three weeks now so, you will not hear any updates from me in that time.

I'd stay away from using stat counters that require costly locking. I'd vote for a local counter instead.

2025-04-16 12:29 UTC, azike commented
Hi! I am back now and pushed two ideas I had within the last two commits. Because of the layering that is going it is a little trickier than thought because directly reporting to other layers is not that straightforward.
The major difference between my two approaches is when to call `stat` to get the current actual filesize. 

1.  First I called it directly at the beginning of `log_writer_flush` and then kept adding the message size report by the write function. However, in this case `stat` is always called even if logrotation is disabled because the `logwriter` does not know about logrotation in gerneral.

2. Get the filesize when (re-)opening a file and store it in `AFFileDestWriter`. The size gets updated by calling `log_pipe_notify` after every message written reporting its output buffer size. This way `stat` is only called once when the file is opened.

In both cases logrotation only checks against this in-memory `cached_filesize`. This seems to work so far, also my testcase works again.

Again there are some subtle points that need attention and there I guess I need some help regarding how to deal with them and to not interfere with the design choices of the project. I will discuess them in the comments below.

2025-04-16 12:37 UTC, azike commented on lib/logwriter.c
> +      if (!log_writer_flush_finalize(self)) {
When reopening the file, the current outgoing buffer needs to be flushed (using the "old" `LogProtoClient`) to write the contents to the file before it gets closed. This is easy when reopen was successful, however, if it failed at this point the old log file may already been closed, and flushing is not possible anymore.
One could add a `logrotate_options` field to the `LogWriter` and do the checks here and only notify `AFFileDestWriter` when logrotation should be performed, but I think that might not be in favor of the abstraction (since `LogWriter` is used not only for files)?

2025-04-16 12:39 UTC, azike commented on modules/affile/affile-dest.c
> +          self->cached_filesize = 0;
What would be the right way to deal with fs errors here? Simply return an ERROR code?

2025-06-04 14:14 UTC, stwalser commented
> Will this patch be included in future versions of syslog-ng?

I would welcome that too.

2025-07-11 08:34 UTC, HofiOne commented
@azike could you please rebase on the latest develop?

2025-07-11 13:17 UTC, HofiOne commented
@azike i guess the `Close` was accidental, am I right?

2025-07-11 13:52 UTC, azike commented
Hi! Yes it was accidental because I had to re-sync my fork. Once I am done rebasing we can re-open it.

2025-07-11 15:17 UTC, HofiOne commented
Apart from the style-check issues, it seems to be building fine, just your test is failing currently

2025-07-14 08:01 UTC, azike commented
I see that you made some changes that are affecting my implementation. 
For now the test still fails, as it seems that somewhere the rotated files fd is not updated and hence the "old" files is still written to.  I need to check further why that happens.

2025-07-14 09:41 UTC, HofiOne commented
> I see that you made some changes that are affecting my implementation. For now the test still fails, as it seems that somewhere the rotated files fd is not updated and hence the "old" files is still written to. I need to check further why that happens.

Yepp, there have been a bunch of changes meanwhile, sorry.

I've made a test build using the `dbld/rules shell-devshell` dev shell and found no issues at all, tested both with autotools and cmake.

Also, I made some tests using the example config you provided in the `Usage` part above, and found similar issues that you mentioned.

I have suspended the review for now and am awaiting your new fixes.

2025-07-14 09:43 UTC, HofiOne requested changes

2025-07-14 09:43 UTC, HofiOne commented on modules/affile/affile-dest.c
> +          self->cached_filesize = 0;
I guess you should use

fstat(fd, &st)

instead above, and treat failure of fstat here as it would be an open error

- log the error
- set open_result FILE_OPENER_RESULT_ERROR_TRANSIENT

2025-07-14 09:43 UTC, HofiOne commented on modules/affile/affile-dest.c
> +  self->cached_filesize+=buf_len;
missing spaces around `+=` operator

2025-07-14 09:43 UTC, HofiOne commented on modules/affile/affile-parser.c
> +  { "rotate",             KW_LOGROTATE_ROTATIONS},
i suggest using something more descriptive as a keyword instead, like `rotations`

2025-07-14 09:43 UTC, HofiOne commented on modules/affile/affile-grammar.ym
> +	| KW_LOGROTATE_SIZE '(' nonnegative_integer ')' {affile_dd_set_logrotate_size(last_driver, $3);}
i suggest using `positive_integer` both here and simply for `KW_LOGROTATE_ROTATIONS`, which will auto check and signal error on negative or 0 values

2025-07-14 09:43 UTC, HofiOne commented on modules/affile/affile-dest.c
> +  if (max_rotations <= 0)
using `positive_integer` in the grammar as i suggested there will guarantee a non-zero positive integer here, you can simply assign as you do now in `affile_dd_set_logrotate_size`

2025-07-16 17:10 UTC, azike commented on modules/affile/affile-dest.c
> +          self->cached_filesize = 0;
Done.

2025-07-16 17:10 UTC, azike commented on modules/affile/affile-dest.c
> +  self->cached_filesize+=buf_len;
Fixed

2025-07-16 17:11 UTC, azike commented on modules/affile/affile-parser.c
> +  { "rotate",             KW_LOGROTATE_ROTATIONS},
Changed it to `rotations`.

2025-07-16 17:11 UTC, azike commented on modules/affile/affile-grammar.ym
> +	| KW_LOGROTATE_SIZE '(' nonnegative_integer ')' {affile_dd_set_logrotate_size(last_driver, $3);}
Done

2025-07-16 17:11 UTC, azike commented on modules/affile/affile-dest.c
> +  if (max_rotations <= 0)
Done

2025-07-16 17:14 UTC, azike commented
I can also build it now using `dbld/rules shell-devshell` and the test is working again?
Maybe you can confirm that it actually works and I was not just lucky.

Also, I added your "small" suggestions.

2025-07-16 19:18 UTC, HofiOne commented
> I can also build it now using `dbld/rules shell-devshell` and the test is working again? Maybe you can confirm that it actually works and I was not just lucky.
> 
> Also, I added your "small" suggestions.

Builds fine now, thanks!
I've also made a quick test, works nicely, it seems.

Tomorrow I will continue the review.
Thank you.

2025-07-17 08:50 UTC, HofiOne commented on modules/affile/logrotate.h
> +gboolean is_logrotate_enabled(LogRotateOptions *logrotate_options);
Please treat this as a C++ class (like for the other modules e.g. the affile destination) and use the name convention we have everywhere for the public class functions

s.g. like

```
logrotate_is_enabled
logrotate_is_pending
logrotate_options_defaults
logrotate_do_rotate
```

or similar

2025-07-17 09:18 UTC, HofiOne commented on modules/affile/logrotate.c
> + * Do renaming in separate thread?
This could work like you described here.

I would add a new option, let the user control this behavior (alternatively, a smart detection of the necessity of threaded rotation can be implemented as well, but that can be tricky, so I would vote for a user-controlled switch)

2025-07-17 09:36 UTC, HofiOne commented on lib/logwriter.c
> +          *write_error = TRUE;
the new proto is leaking here this way, we should release the proto

2025-07-17 10:04 UTC, HofiOne commented on lib/logwriter.c
> +            {
I understand the rationale behind using {} consistently, even for a single-line expression, but please maintain consistency at least within the current file (especially in a given function).
In this file, it is not used; please adhere to this behavior.

2025-07-17 10:13 UTC, HofiOne commented on lib/logwriter.c
> +          // TODO: need to know if logrotation is pending and flush before potential error!
I guess this one is not needed here anymore

2025-07-17 10:18 UTC, HofiOne commented on lib/logwriter.c
> +          log_writer_logrotate(self, msg_len, &write_error);
write_error can be set to TRUE here if the flush did not succeed in log_writer_logrotate, we should handle that too and return with the status code, so log_writer_logrotate should not be void (see the last line of this function, which returns the result of log_writer_flush_finalize)

2025-07-17 11:16 UTC, HofiOne commented on modules/affile/affile-dest.c
> +          open_result = FILE_OPENER_RESULT_ERROR_TRANSIENT;
*p will leak here again, we should release the proto

2025-07-17 12:15 UTC, HofiOne commented on modules/affile/affile-dest.c
> + * Alternativly the reopened could be triggered through a main-thread call here:
this can be removed now i guess

2025-07-17 13:27 UTC, HofiOne commented on modules/affile/affile-dest.c
> +      // we need to flush the buffer here!
it is happening in the caller now (log_writer_logrotate)
so we do not need this here anymore I guess

2025-07-17 13:43 UTC, HofiOne commented on modules/affile/affile-dest.c
> +  if (is_logrotate_enabled(logrotate_options) && is_logrotate_pending(logrotate_options, self->cached_filesize))
actually this must be 3 conditions

enabled, required, pending

the current pending must be called required

a future, new pending must really check if there was a pending, whatever reason not finished rotation in progress

an already in progress rotation, especially the one that already rotated the file names but still waiting for an earlier failed re_open, must not rotate again

please see bellow how the latter can still happen currently

2025-07-17 13:50 UTC, HofiOne commented on modules/affile/affile-dest.c
> +          /* TODO: Do something */
as I mentioned, the only reason we can get here a FILE_OPENER_RESULT_ERROR_PERMANENT error is a bogus file path
the targeted, main file path cannot change just because of the log rotate
if the path was fine initially, it must be fine here as well

anyway

if this happens we are in trouble currently

try replacing the line 159 with

```
  static int opened_once = 0;
  FileOpenerResult open_result = (opened_once++ == 0 ? file_opener_open_fd(self->owner->file_opener, self->filename, AFFILE_DIR_WRITE, &fd) : FILE_OPENER_RESULT_ERROR_PERMANENT);
```

this will simulate a FILE_OPENER_RESULT_ERROR_PERMANENT error here

in this case the whole flow is screws currently, this will remove all the logs and tries to open the new one in a loop without waiting like the scheduled re-open


I think this case (and a failed do_logrotate as well, depending on what part is failed)  should signal back the reason of the failure to the caller (log_writer_logrotate)
and the caller should cleanup the current proto instance to prevent message loss
e.g. the ones that are continuously written to the already renamed (and sometimes deleted) old log file

2025-08-04 06:51 UTC, azike commented on modules/affile/logrotate.h
> +gboolean is_logrotate_enabled(LogRotateOptions *logrotate_options);
Done

2025-08-04 06:51 UTC, azike commented on lib/logwriter.c
> +          *write_error = TRUE;
fixed now

2025-08-04 06:52 UTC, azike commented on modules/affile/affile-dest.c
> +          open_result = FILE_OPENER_RESULT_ERROR_TRANSIENT;
fixed now

2025-08-04 06:52 UTC, azike commented on modules/affile/affile-dest.c
> + * Alternativly the reopened could be triggered through a main-thread call here:
removed

2025-08-04 06:53 UTC, azike commented on modules/affile/logrotate.c
> + * Do renaming in separate thread?
Maybe we could keep this idea for a separate PR and get the non-threaded version ready.
Also an option to enable compression would be beneficial.

2025-08-04 06:57 UTC, azike commented on modules/affile/affile-dest.c
> +          /* TODO: Do something */
I simulated the issues as you suggested and I agree on the current faulty implementation.

Two fixes I added:

1) The call to affile_dw_logrotate via log_pipe_notify now returns with an error code, in case the reopen was not successful, preventing log_writer_flush to continue writing the wrong file.

2) I added a pending flag to logrotate_options which is reset once the new logfile has been reopened, to prevent multiple rotations.

2025-08-04 06:57 UTC, azike commented
Hi!
Thanks for the review, I surely missed some important parts.
Nevertheless I implemented your suggestions, so please have a look.

2025-08-04 06:59 UTC, azike commented on lib/logwriter.c
> +      log_writer_free_proto(self);
Can we do better, than just free the proto client here?

2025-08-18 12:33 UTC, HofiOne commented
> Hi! Thanks for the review, I surely missed some important parts. Nevertheless I implemented your suggestions, so please have a look.

Thank you.
I'm back from my holiday, I'll do my best to get this reviewed this week.

@azike Could you please fix the build errors till that?

2025-08-21 08:24 UTC, azike commented
Hi! Should be fixed now.

2025-08-25 09:18 UTC, HofiOne commented on lib/logpipe.h
> +#define NR_ERROR       0x0002
I'd swap the order of NR_ERROR and NR_STOP_ON_EOF, changing the value is not an issue here, I do not think these persist anywhere, keeping NR_OK and NR_ERROR next to each other (and the 0 and 1 values) makes more sense to me

2025-08-25 09:51 UTC, HofiOne commented on modules/affile/logrotate.c
> +  if (logrotate_options == NULL)
I wonder when it could happen that the logrotate_options are not yet allocated?

Anyway, you could simplify these 3 func e.g.

`return logrotate_options && logrotate_options->enable;`

2025-08-25 12:59 UTC, HofiOne commented on modules/affile/logrotate.c
> +
as step (0), we might want to check first if  `get_log_file_name(filename, 1)` exists
if not, we can skip all the rotations here, and go to step (3) immediately

2025-08-25 13:00 UTC, HofiOne commented on modules/affile/logrotate.c
> +  if (g_file_test(current_filename, G_FILE_TEST_EXISTS))
step (1) is not needed if `get_log_file_name(filename, logrotate_options->max_rotations - 1)` does not exist

2025-08-25 13:45 UTC, HofiOne commented on lib/logwriter.c
> +      log_writer_free_proto(self);
Probably, we will not need this after all.
Please see my suggestions in logrotate_do_rotate of modules/affile/logrotate.c
A proper rotation logic might prevent log file loss/over rotating.

Also, leaving the proto client alone will ensure the inner logic suspends the writer on flush error.

Apart from that, an earlier problem still exists. If the NC_LOGROTATE notification handler fails, the writer gets stuck, even if the `log_writer_free_proto(self);` line is not presented (which is a bit better case, as the writer suspension/and reopening is happening in that case, but still not perfect)
For a reproduction, simply, please return with `LR_ERROR from `logrotate_do_rotate` when first time called.


EDIT: Ok, the latter is not fully true, I was testing with a `example_msg_generator` that seems to stop sending, once the flow is suspended, but no issues with e.g. a system source it seems.

So, `log_writer_free_proto(self);` should not be used here if we'd like to automatically suspend/resume/reopen the writer after a logrotate (flush) error, we just have to make sure the rotation logic will not fail in any circumstances.

2025-08-25 16:12 UTC, HofiOne commented on tests/light/functional_tests/destination_drivers/file_destination/test_file_destination.py
> +        assert (size < max_size + epsilon)
Could you please add test cases for failing rotation attempts somehow?

2025-08-28 09:07 UTC, azike commented on tests/light/functional_tests/destination_drivers/file_destination/test_file_destination.py
> +        assert (size < max_size + epsilon)
Is there a logic that reopens the log file if the file gets deleted? Or would the writer simply be stuck in that case?

2025-08-28 11:12 UTC, HofiOne commented on lib/logwriter.c
> +      //log_writer_free_proto(self); // clean proto here?
as i mentioned, cleaning the proto will prevent the automatic retry from taking effect

2025-08-28 11:29 UTC, HofiOne commented on modules/affile/logrotate.c
> +    return LR_ERROR;
This must not be an error; otherwise, the writer gets stuck in an infinite loop.
If someone deleted the current log file meanwhile, it should not be our problem.
I suggest to log here a warning, and returning with LR_SUCCESS.
The new log file will be re-created (either immediately, or after `time-reap()` value passed, for files using templates in its name) by the writer (of course, the logs are written to the deleted file meanwhile will be lost, but it is normal, as its container file is deleted)

2025-08-28 11:57 UTC, HofiOne commented
@azike you can ignore the fedore-rawhide issues; hopefully, it will be fixed by the maintainers soon

2025-08-28 13:23 UTC, HofiOne commented on modules/affile/logrotate.c
> +      msg_error("Error could not rotate log file because it does not exist",
Could you please revise the error message (like this), and use a full sentence, here s.g. like
"Error rotating log file because it does not exist"

2025-08-28 13:48 UTC, azike commented on modules/affile/logrotate.c
> +    return LR_ERROR;
Ah! You are right, I was thinking too complicated here.

2025-08-28 14:07 UTC, HofiOne commented on modules/affile/logrotate.c
> +
Please remove double empty lines

2025-08-28 14:17 UTC, HofiOne commented on modules/affile/logrotate.c
> +      if (res == -1)
Could you please compare against 0, as I can remember the standard says these can return 0 or non-zero values, -1 is not mentioned explicitly

2025-08-28 14:46 UTC, HofiOne commented on tests/light/functional_tests/destination_drivers/file_destination/test_logrotate_all_messages_received.py
> +    sleep(1)
i'm not sure if it's always enough, github can assign very slow machines sometimes

2025-08-28 14:48 UTC, HofiOne commented on modules/affile/logrotate.c
> +      msg_warning("Main log file does not exist",
Please replace the log string by s.g like
"WARNING: Logrotate could not find the main log file"
as the warning lines have WARNING: prefix everywhere, and mentioning Logrotate can identify the sender better

2025-09-02 06:32 UTC, azike commented on modules/affile/logrotate.c
> +      msg_error("Error could not rotate log file because it does not exist",
Done

2025-09-02 06:32 UTC, azike commented on tests/light/functional_tests/destination_drivers/file_destination/test_logrotate_all_messages_received.py
> +    sleep(1)
I increased the wait time to 5s.

2025-09-02 06:33 UTC, azike commented on modules/affile/logrotate.c
> +      if (res == -1)
In the man page it says that -1 is returned on error, but I changed it to compare against != 0.

2025-09-02 06:33 UTC, azike commented on modules/affile/logrotate.c
> +      msg_warning("Main log file does not exist",
Done

2025-09-02 10:42 UTC, HofiOne commented
@azike The current state LGTM. Could you please update the corresponding documentation parts

https://github.com/syslog-ng/syslog-ng.github.io/blob/master/doc/_admin-guide/070_Destinations/040_File/000_File_destination_options.md

as well? Thank you in advance!

2025-09-03 14:25 UTC, therandomstring requested changes

2025-09-03 14:25 UTC, therandomstring commented on modules/affile/logrotate.c
> + * Copyright (c) 2024 Balabit
Since this is an outside contribution, adding a Balabit/One Identity copyright is not necessary. I recommend you to copyright the file under your own name and add the file to `tests/copyright/policy` under the correct section.

(This applies to all of the new headers)

2025-09-03 14:25 UTC, therandomstring commented on lib/logpipe.h
> +#define NR_STOP_ON_EOF 0x0002
Please confirm this does not break `modules/affile/wildcard-file-reader.c` #L122

2025-09-03 14:25 UTC, therandomstring commented on modules/affile/affile-dest.c
> +      logrotate_options->pending = TRUE;
Since the permanent error path does not reset  this, effectively disabling the rotation on error. The error message could reflect this.

2025-09-03 14:25 UTC, therandomstring commented on news/feature-5191.md
> +affile: add support for filesize based logrotation
Optional: A small config snippet would be welcome in a feature news file.

2025-09-03 16:23 UTC, HofiOne commented on lib/logpipe.h
> +#define NR_STOP_ON_EOF 0x0002
this won't break anything I guess, this one is not persistent anywhere as far as I could see

2025-09-04 12:56 UTC, HofiOne approved these changes
LGTM if @therandomstring's concerns are resolved

2025-09-04 15:53 UTC, azike commented
Hi! I pushed the changes. Please check if those are resolved now.

2025-09-04 15:57 UTC, azike commented
> @azike The current state LGTM.
> 
> Could you please update the [corresponding documentation parts](https://github.com/syslog-ng/syslog-ng.github.io/blob/master/doc/_admin-guide/070_Destinations/040_File/000_File_destination_options.md) as well? Thank you in advance!


I forked the repo and started to add the documentation, but I was wondering what I should write for `type`? Does `parameter list of the logrotate() option` suffice plus describing the parameters below in the descriptions part?

2025-09-04 16:06 UTC, HofiOne commented
> > @azike The current state LGTM.
> > Could you please update the [corresponding documentation parts](https://github.com/syslog-ng/syslog-ng.github.io/blob/master/doc/_admin-guide/070_Destinations/040_File/000_File_destination_options.md) as well? Thank you in advance!
> 
> I forked the repo and started to add the documentation, but I was wondering what I should write for `type`? Does `parameter list of the logrotate() option` suffice plus describing the parameters below in the descriptions part?

@azike you can follow the schema that can be seen in the final, rendered version

like

https://syslog-ng.github.io/admin-guide/070_Destinations/040_File/000_File_destination_options

2025-09-04 16:52 UTC, HofiOne commented
> > > @azike The current state LGTM.
> > > Could you please update the [corresponding documentation parts](https://github.com/syslog-ng/syslog-ng.github.io/blob/master/doc/_admin-guide/070_Destinations/040_File/000_File_destination_options.md) as well? Thank you in advance!
> > 
> > 
> > I forked the repo and started to add the documentation, but I was wondering what I should write for `type`? Does `parameter list of the logrotate() option` suffice plus describing the parameters below in the descriptions part?
> 
> @azike you can follow the schema that can be seen in the final, rendered version
> 
> like
> 
> https://syslog-ng.github.io/admin-guide/070_Destinations/040_File/000_File_destination_options

`disk-buffer()` is a good example of an option with sub-options

source https://github.com/syslog-ng/syslog-ng.github.io/blob/master/_includes/doc/admin-guide/options/disk-buffer.md

rendered like https://syslog-ng.github.io/admin-guide/070_Destinations/040_File/000_File_destination_options#disk-buffer

2025-09-05 06:05 UTC, azike commented
Do you also need tests for the config parser? Like here https://github.com/syslog-ng/syslog-ng/blob/develop/modules/affile/tests/test_wildcard_source.c?

2025-09-05 07:41 UTC, HofiOne commented
> Do you also need tests for the config parser? Like here https://github.com/syslog-ng/syslog-ng/blob/develop/modules/affile/tests/test_wildcard_source.c?

@azike it would be nice and useful

EDIT: I suggest moving that to the next iteration. I'll merge this now, thanks.

2025-09-05 08:16 UTC, therandomstring approved these changes
LGTM

2025-09-05 08:31 UTC, merged

2025-09-05 08:34 UTC, azike commented
Cool! Thanks guys.

2025-09-05 10:26 UTC, HofiOne commented
@azike Thanks for your work! Unfortunately, some errors occur now in our Kira tests that should have happened in the earlier runs here. I investigate how earlier the Kira runs did not find the problem, and what the reason is of the failures.